name: AutoSign
on:
  push:
    branches: main
  schedule:
    - cron: "41 14 * * *"
jobs:
  Sketchup_Auto_Sign:
    name: sketchup Auto Sign
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci	
      - name: Run AutoSign
        run: |
          node AutoSign.js
