name: AutoSign
on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: "01 16 * * *"
jobs:
  Sketchup_Auto_Sign:
    name: sketchup Auto Sign
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci	
      - name: Run AutoSign-sketchup
        run: |
          node AutoSign-sketchup.js
      - name: Run AutoSign-sehuatang
        run: |
          node AutoSign-sehuatang.js      
