name: "AutoSign"
on:
  push: # 触发机制为push操作
    branches: main
  schedule: # 触发机制为定时任务
    - cron: "30 19 * * *" # 每天03点30分自动执行（默认UTC时区）
jobs:
  AutoSign:
    runs-on: ubuntu-latest # 运行环境为最新的Ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 使用官方提供的checkout 2.0版本获取代码
      - name: Setup node.js
        uses: actions/setup-node@v1 # 使用官方提供的setup-node 1.0版本配置node环境
        with:
          node-version: "14.x" # 使用node 14版本作为运行环境
      - name: Install dependencies
        run: npm install # 安装依赖
      - name: Run AutoSign
        env:
          SEHUATANG_COOKIES: ${{secrets.SEHUATANG_COOKIES}}
          BILIBILI_COOKIES: ${{secrets.BILIBILI_COOKIES}}
          POJIE52_COOKIES: ${{secrets.POJIE52_COOKIES}}
          ZODGAME_COOKIES: ${{secrets.ZODGAME_COOKIES}}
          SKETCHUPBAR_COOKIES: ${{secrets.SKETCHUPBAR_COOKIES}}
          BARK_URL: ${{secrets.BARK_URL}}
        run: |
          node autoSign.js
